apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: node-ingress-policy
spec:
  podSelector:
    matchLabels:
      app: kairos-node
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: kairos-gateway
        - podSelector:
            matchLabels:
              app: kairos-cli
        - podSelector:
            matchLabels:
              app: kairos-explorer
        - podSelector:
            matchLabels:
              app: kairos-node
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 9080